---
title: "TidyTuesdayGreatAmericanBeerFestival"
author: "Jeff Grayum"
date: "12/1/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries:
```{r}
library(tidyverse)
library(tidytuesdayR)
library(ggthemes)
library(tvthemes)
library(scales)
library(glue)
library(extrafont)
```

Loading data:
```{r}
tuesdata <- tidytuesdayR::tt_load('2020-10-20')

beer_awards <- tuesdata$beer_awards %>%
  mutate(state = str_to_upper(state),
         medal = fct_relevel(medal, c("Bronze", "Silver"))) 
  

gold_medals <- beer_awards %>%
  filter(medal == "Gold") %>%
  view()
```

Initial analysis and some visualizations:
```{r}
beer_awards %>%
  view()

beer_awards %>%
  distinct(year)

gold_medals %>%
  count(brewery, sort = TRUE) %>%
  head(20) %>%
  mutate(brewery = fct_reorder(brewery, n)) %>%
  ggplot(aes(n, brewery)) + 
  geom_col() +
  labs(title = "Which breweries have won the most gold medals at the Great American Beer Festival",
       subtitle = "Gold medals awarded from 1987 - 1920",
       x = "Total gold medals",
       y = "",
       caption = "Source: Great American Beer Festival") +
  theme_simpsons() 

beer_awards %>%
  count(brewery, sort = TRUE) %>%
  head(20) %>%
  mutate(brewery = fct_reorder(brewery, n)) %>%
  ggplot(aes(n, brewery)) + 
  geom_col() +
  labs(title = "The twenty most awarded breweries in the North American Beer Festival",
       subtitle = "Total medals awarded from 1987 - 1920",
       x = "Total medals",
       y = "",
       caption = "Source: Great American Beer Festival") +
  theme_simpsons() 

beer_awards %>%
  count(city, sort = TRUE) %>%
  head(20) %>%
  mutate(city = fct_reorder(city, n)) %>%
  ggplot(aes(n, city)) +
  geom_col() +
  theme_simpsons() +
  labs(title = "Which cities brew the best beer?",
       x = "Number of times a brewery has medaled at Great American Beer Festival",
       y = "",
       caption = "Source: Great American Beer Festival 1987 - 2020")

beer_awards %>%
  count(state, sort = TRUE) %>%
  head(20) %>%
  mutate(state = fct_reorder(state, n)) %>%
  ggplot(aes(n, state)) +
  geom_col() +
  theme_simpsons() +
  labs(title = "Which States brew the best beer?",
       x = "Number of times a brewery has medaled at Great American Beer Festival",
       y = "",
       caption = "Source: Great American Beer Festival 1987 - 2020")


beer_awards %>%
  count(beer_name, brewery, sort = TRUE) %>%
  head(20) %>%
  mutate(beer_name = fct_reorder(beer_name, n)) %>%
  ggplot(aes(n, beer_name)) +
  geom_col() +
  labs(title = "What are the most highly-awarded beers at the Great American Beer Festival?",
       x = "Number of medals won",
       y = "",
       caption = "Source: Great American Beer Festival 1987 - 2020") +
  theme_simpsons()

gold_medals %>%
  count(beer_name, brewery, sort = TRUE) %>%
  head(5) %>%
  mutate(beer_name = fct_reorder(beer_name, n)) %>%
  ggplot(aes(n, beer_name)) +
  geom_col() +
  labs(title = "Which beers have won the most gold medals at the Great American Beer Festival?",
       x = "Number of medals won",
       y = "",
       caption = "Source: Great American Beer Festival 1987 - 2020") +
  theme_simpsons()

beer_awards %>%
  group_by(year) %>%
  count(category, sort = TRUE) %>%
  View()

beer_awards %>%
  filter(category == "IPA") %>%
  count(beer_name, sort = TRUE) %>%
  head(5) %>%
  view()
  mutate(beer_name = fct_reorder(beer_name, n)) %>%
  ggplot(aes(n, beer_name)) +
  geom_col()
  
  beer_awards %>%
    filter(category == "American-Style Pale Ale") %>%
    count(brewery, sort = TRUE) %>%
    head(10) %>%
    mutate(brewery = fct_reorder(brewery, n)) %>%
    ggplot(aes(n, brewery)) +
    geom_col() +
    labs(title = "What brewery makes the best IPA?",
         x = "Number of medals",
         y = "", 
         caption = "Source: Great American Beer Festival 1987 - 2020") +
    theme_simpsons()
```

Okay, now for David's take.
```{r}
beer_awards %>%
  count(year) %>%
  ggplot(aes(year, n)) + 
  geom_col() +
  labs(title = "How many awards were handed out each year during the Great American Beer Festival?",
       x = "Year",
       y = "Number of medals awarded",
       caption = "Sourch: Great American Beer Festival 1987 - 2020") +
  theme_simpsons()

beer_awards %>%
  count(brewery, city, state, sort = TRUE) 

beer_awards %>%
  count(category, sort = TRUE)

beer_awards %>%
  filter(category == "Bock") %>%
  view()
```

What are the most awarded beers?
```{r}
beer_awards %>%
  count(beer_name, brewery, sort = TRUE)

beer_counts <- beer_awards %>%
  count(beer_name, brewery, medal, city, state) 

beer_counts %>%
  pivot_wider(names_from = medal, values_from = n,
              values_fill = list(n = 0)) %>%
  mutate(total = Bronze + Silver + Gold) %>%
  arrange(desc(total))
```

HERE'S A REALLY COOL TRICK ON HOW TO USE FILTER() AND FCT_LUMP() TO SHOW ONLY THE TWELVE MOST AWARDED BEERS!!
```{r}
beer_counts %>%
  mutate(beer_name = glue("{ beer_name } ({ brewery })")) %>%
  filter(fct_lump(beer_name, 20, w = n, ties.method = "first") != "Other")  %>%
  mutate(beer_name = fct_reorder(beer_name, n, sum)) %>%
  ggplot(aes(n, beer_name, fill = medal)) +
  geom_col() +
  labs(title = "The most awarded beers at the Great American Beer Festival",
       x = "Number of Awards",
       y = "",
       fill = "", 
       caption = "Source: Great American Beer Festival, 1987 - 2020") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  scale_fill_manual(values = myColors)

myColors <- c("#a37d0b", "#9bc4cc", "#ebda21")
```

What breweries win the most awards?
```{r}
beer_awards %>%
  count(brewery, sort = TRUE)

by_brewery <- beer_awards %>%
  group_by(brewery) %>%
  summarize(n_medals = n(),
            n_beers = n_distinct(beer_name),
            weighted_medals = sum(as.integer(medal)), #medals are already factored
            n_gold = sum(medal == "Gold")) %>% 
  arrange(desc(n_medals)) %>%
  view()

beer_awards %>%
  count(brewery, medal) %>%
  filter(fct_lump(brewery, 16, w = n) != "Other") %>%
  mutate(brewery = fct_reorder(brewery, n, sum)) %>%
  ggplot(aes(n, brewery, fill = medal)) +
  geom_col() +
  theme_fivethirtyeight() +
  labs(title = "The most awarded breweries at the Great American Beer Festival",
       x = "Number of awards",
       y = "",
       caption = "Source: Great American Beer Festival, 1987 - 2020",
       fill = "") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  scale_fill_manual(values = myColors)
```

Now, let's look at the states!
```{r}
beer_awards %>%
  count(state, sort = TRUE)

# SET OF INTERNAL DATA CALLED STATE.ABB!!
state.abb

#We can compare it to our count of states using setdiff() to see if any are missing.
setdiff(state.abb, beer_awards$state)

#We see that West Virginia has never won an award.  Probably because this isn't a moonshine data set.

#Let's look at per capita award winning beers


```

TO DO
-Choropleth (colored map) 
-Per-capita award winning beers

